### PR TITLE
Fixed version check in wrong directory

### PR DESCRIPTION
**Pull request by neojaw**
If the library is built as a subdirectory, the current CMake code extracts the version number of the parent project instead (if available). Git command must be invoked in the *current* source directory.

The remaining occurrences of `CMAKE_SOURCE_DIR` in the project concern installer creation which is probably fine.

### CODE REVIEW

**Comment by lola-masson** [comment]
Hi @neojaw,

Thank you for your contribution! It seems like you need to rebase your branch to the last version of main. Or were you hoping to provide a patch to an older release version? Your PR currently contains 527 changes.

**Comment by neojaw** [comment]
Hi @lola-masson, my PR *was* based on the latest `main`, it seems to me like @BigBoot did force pushes in your repo and now my fork is out of sync?
```
This branch is 1823 commits ahead of, 1919 commits behind ifm/ifm3d:main.
```
I'll try to rebase it...

**Comment by BigBoot** [comment]
Hi @neojaw yes you're correct we had to force push due to an issue with the sync from our internal repo. I can merge you're changes manually if you're ok with that?

**Comment by neojaw** [comment]
Nevermind, already fixed it. Looks good now.

**Pull request merged**
